apiVersion: v1 
kind: service
metadata:
  - name: service
    labels: 
      app: nginx
      ver: 1.23
spec:
  type: LoadBalancer
  ports:
    - name: loadbalance_service
      port: 80
      targetPort: 35001
    